fixed: user email gets added to food history database
tenzin1308/Nutrimental pull request #93
Opened 2022-03-23 20:59 UTC by tanzil7

2022-03-23 21:24 UTC, HAFSAnCR7 approved these changes

2022-03-24 20:24 UTC, JustinParkCS requested changes
The action of adding a user to the foodhistorydb upon signup should be within the .then() (line 47)

2022-03-28 14:37 UTC, JustinParkCS approved these changes

2022-03-28 16:29 UTC, tenzin1308 approved these changes

2022-03-28 16:29 UTC, merged